#!/bin/bash

set -e -x

cd ~/cimr/
python3 setup.py build
sudo python3 setup.py install

# Remove intermediate files generated by the build/install commands
sudo rm -rf ./build/ ./cimr.egg-info/ ./dist/
